name: Update Incomes and Expenses Job

on:
  schedule:
    - cron: "0 6,12,22 * * *"  # Executa todos os dias às 06:00 UTC
  workflow_dispatch:  # Permite rodar manualmente pelo GitHub Actions

jobs:
  update-incomes-and-expenses:
    runs-on: ubuntu-latest

    steps:
      - name: Code Checkout
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install requirements
        run: pip install -r ./docs/requirements.txt

      - name: Run Notion Update Incomes
        env:
          NOTION_API_TOKEN: ${{ secrets.NOTION_API_TOKEN }}
          NOTION_DATABASE_ANT_INCOMES_INPUT_ID: ${{ secrets.NOTION_DATABASE_ANT_INCOMES_INPUT_ID }}
          NOTION_DATABASE_ANT_EXPENSES_INPUT_ID: ${{ secrets.NOTION_DATABASE_ANT_EXPENSES_INPUT_ID }}
          NOTION_DATABASE_ANT_INCOMES_ID: ${{ secrets.NOTION_DATABASE_ANT_INCOMES_ID }}
          NOTION_DATABASE_ANT_EXPENSES_ID: ${{ secrets.NOTION_DATABASE_ANT_EXPENSES_ID }}
          NOTION_DATABASE_ANT_PERIODICAL_INCOMES_ID: ${{ secrets.NOTION_DATABASE_ANT_PERIODICAL_INCOMES_ID }}
          NOTION_DATABASE_ANT_PERIODICAL_EXPENSES_ID: ${{ secrets.NOTION_DATABASE_ANT_PERIODICAL_EXPENSES_ID }}
          NOTION_DATABASE_ANT_CATEGORY_ID: ${{ secrets.NOTION_DATABASE_ANT_CATEGORY_ID }}
          NOTION_DATABASE_ANT_PAYMENT_ID: ${{ secrets.NOTION_DATABASE_ANT_PAYMENT_ID }}
        run: python -c "import asyncio; from src.main import update_incomes; asyncio.run(update_incomes())"

      - name: Run Notion Update Expenses
        env:
          NOTION_API_TOKEN: ${{ secrets.NOTION_API_TOKEN }}
          NOTION_DATABASE_ANT_INCOMES_INPUT_ID: ${{ secrets.NOTION_DATABASE_ANT_INCOMES_INPUT_ID }}
          NOTION_DATABASE_ANT_EXPENSES_INPUT_ID: ${{ secrets.NOTION_DATABASE_ANT_EXPENSES_INPUT_ID }}
          NOTION_DATABASE_ANT_INCOMES_ID: ${{ secrets.NOTION_DATABASE_ANT_INCOMES_ID }}
          NOTION_DATABASE_ANT_EXPENSES_ID: ${{ secrets.NOTION_DATABASE_ANT_EXPENSES_ID }}
          NOTION_DATABASE_ANT_PERIODICAL_INCOMES_ID: ${{ secrets.NOTION_DATABASE_ANT_PERIODICAL_INCOMES_ID }}
          NOTION_DATABASE_ANT_PERIODICAL_EXPENSES_ID: ${{ secrets.NOTION_DATABASE_ANT_PERIODICAL_EXPENSES_ID }}
          NOTION_DATABASE_ANT_CATEGORY_ID: ${{ secrets.NOTION_DATABASE_ANT_CATEGORY_ID }}
          NOTION_DATABASE_ANT_PAYMENT_ID: ${{ secrets.NOTION_DATABASE_ANT_PAYMENT_ID }}
        run: python -c "import asyncio; from src.main import update_expenses; asyncio.run(update_expenses())"

